resources:
- name: hello-trigger
  type: git
  source: 
    uri:  https://github.com/beniwal-devika/Concourse/blob/master.git


jobs:
- name: job say hello
  public: true
  plan: 
    - get: hello-trigger
    - task: Hello trigger example
      file: hello-trigger/hello.yml





