resources:
- name: res1
  type: git
  source: 
    branch: master
    uri:  https://github.com/beniwal-devika/Concourse.git
    


jobs:
- name: Job say hello
  public: true
  plan: 
    - get: res1
    - task: Trigger resource
      file: res1/hello.yml








