resources:
- name: res1
  type: git
  source:
    uri: https://github.com/beniwal-devika/Concourse.git
    branch: master

jobs:
- name: run create file
  public: true
  plan:
  - get: res1
  - task: create file 
    file: res1/3_pass_output_as_input/create.yml
  - task: show file 
    file: res1/3_pass_output_as_input/show.yml


