resources:
- name: res
  type: git
  source: 
   uri: https://github.com/beniwal-devika/Concourse.git
- name: res-gist
  type: git
  source:
   uri: 
   branch: master
   private_key: |
    
jobs:
- name: Pull and push github repo to remote location
  serial: true
  plan: 
  - get: res
  - get: res-gist
  - task: Intermediate file
    file: res/4_pull_push_github_repo/intermediate.yml
  - put: res-gist
    params: {repository: updated-gist}
